apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata: 
      labels: auth
    
    spec:
      containers:
        - name: auth
          image: codeintensive/auth
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret      
