version: '3'

services:
  auth:
    container_name: auth
    build:
      context: ..
      dockerfile: ./Dockerfile
    pull_policy: never
    ports:
      - 5000:5000
    env_file:
      - .env
    
  